apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: burguer-app
  name: burguer-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: burguer-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: burguer-app
    spec:
      containers:
        - env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: secret-burguer51
                  key: MONGO_URL
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret-burguer51
                  key: MONGO_DATABASE
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: secret-burguer51
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-burguer51
                  key: MONGO_PASSWORD
          image: 742943855162.dkr.ecr.us-east-1.amazonaws.com/payment-51-burguer-app:latest
          imagePullPolicy: IfNotPresent
          name: payment-51-burguer-app
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /manage/health
              port: 8080
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /manage/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30