apiVersion: v1
kind: Service
metadata:
  labels:
    app: burguer-app
  name: burguer-app
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30789
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: burguer-app
  sessionAffinity: None