version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: 51-burguer-app
    container_name: 51-burguer-app
    restart: always
    ports:
      - "8787:8080"
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data/:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
